//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RBackup {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class RBackup : global::System.Configuration.ApplicationSettingsBase {
        
        private static RBackup defaultInstance = ((RBackup)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RBackup())));
        
        public static RBackup Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pg_dumpKlasoru {
            get {
                return ((string)(this["pg_dumpKlasoru"]));
            }
            set {
                this["pg_dumpKlasoru"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string postgrePort {
            get {
                return ((string)(this["postgrePort"]));
            }
            set {
                this["postgrePort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string postgreSifre {
            get {
                return ((string)(this["postgreSifre"]));
            }
            set {
                this["postgreSifre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string postgreSunucu {
            get {
                return ((string)(this["postgreSunucu"]));
            }
            set {
                this["postgreSunucu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal yedeklemeSuresi {
            get {
                return ((decimal)(this["yedeklemeSuresi"]));
            }
            set {
                this["yedeklemeSuresi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string postgreVeritabani {
            get {
                return ((string)(this["postgreVeritabani"]));
            }
            set {
                this["postgreVeritabani"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool otomatikYedekleCheckbox {
            get {
                return ((bool)(this["otomatikYedekleCheckbox"]));
            }
            set {
                this["otomatikYedekleCheckbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string postgreKullanici {
            get {
                return ((string)(this["postgreKullanici"]));
            }
            set {
                this["postgreKullanici"] = value;
            }
        }
    }
}
